import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { SwitchTheme } from "@/components/common/SwitchThemeButton";
import { CustomTabs, type TabProp, NonEmptyArray } from "@/components/common/CustomTabs";
import { CustomCard } from "@/components/common/CustomCard";
import TagList from "@/components/common/TagList";
import { getAllPosts } from "@/lib/post";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const TabProps: NonEmptyArray<TabProp> = [
    {
        tabName: "Home",
        tabLink: "/",
    },
    {
        tabName: "Work",
        tabLink: "/blog/tag/works",
    },
    {
        tabName: "About",
        tabLink: "/about",
    },
];

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // Tag Cardに表示するタグを取得する
    const allPosts = await getAllPosts();
    const allTags = allPosts
        .map((post) => {
            return post.tag;
        })
        .flat();
    return (
        <html lang="ja" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased w-full grid-bg-light dark:grid-bg-dark grid grid-cols-3 `}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <div className="col-span-1 flex flex-col gap-5 m-5">
                        <CustomCard title={"About"}>
                            <div className="flex flex-col items-center gap-3 mb-3">
                                <div className="w-16 h-16 rounded-full bg-gradient-to-br from-vivid to-vivid-end flex items-center justify-center text-white text-2xl font-bold select-none">
                                    D
                                </div>
                                <h1 className="text-xl font-bold bg-gradient-to-r from-vivid to-vivid-end bg-clip-text text-transparent">
                                    DEV活
                                </h1>
                            </div>
                            <p className="text-sm text-muted-foreground leading-relaxed text-center">
                                Web系ソフトウェアエンジニアを志望。
                                開発記録や個人的な技術に対する思いを綴ります。
                            </p>
                            <div className="flex flex-wrap gap-1.5 justify-center mt-3 mb-1">
                                <span className="text-xs px-2 py-0.5 rounded-full bg-vivid/10 text-vivid border border-vivid/20">個人開発</span>
                                <span className="text-xs px-2 py-0.5 rounded-full bg-vivid/10 text-vivid border border-vivid/20">Arch Linux</span>
                                <span className="text-xs px-2 py-0.5 rounded-full bg-vivid/10 text-vivid border border-vivid/20">設計</span>
                            </div>
                        </CustomCard>
                        <CustomCard title={"Tag"}>
                            <TagList tags={allTags} />
                        </CustomCard>
                    </div>
                    <div className="col-span-2">
                        <div className="w-full border-b flex flex-row justify-between items-center sticky top-0 z-10 backdrop-blur-md bg-background/80">
                            <div className="flex flex-row items-center gap-0.5">
                                <CustomTabs params={TabProps} />
                            </div>
                            <SwitchTheme />
                        </div>
                        <div className="container mx-auto my-5">{children}</div>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
